version: '3.1'
services:
  db:
    container_name: mall-shop-mysql
    image: mysql
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
